# Generated by Django 5.1.1 on 2024-10-18 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_useralert_userloginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/images/"),
        ),
        migrations.AddField(
            model_name="course",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="courses/pdfs/"),
        ),
    ]
